# Generated by Django 5.2 on 2025-04-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Journal", "0002_remove_dayentry_last_modified_alter_rowentry_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayentry",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
