# Generated by Django 5.2 on 2025-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="date",
        ),
        migrations.AddField(
            model_name="list",
            name="list",
            field=models.CharField(default="Tasks", max_length=30),
        ),
    ]
