# Generated by Django 5.2 on 2025-04-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_list_date_list_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="list",
            new_name="listname",
        ),
    ]
