# Generated by Django 5.2 on 2025-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_rename_list_list_listname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-completed", "date", "start_time", "-priority"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default=None),
        ),
    ]
