# Generated by Django 5.2 on 2025-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_task_options_rename_time_task_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
