# Generated by Django 5.2 on 2025-04-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed", "date", "start_time", "-priority"]},
        ),
        migrations.AddField(
            model_name="list",
            name="to_journal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtask",
                to="todo.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parenttask",
                to="todo.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                    (6, "Level 6"),
                    (7, "Level 7"),
                    (8, "Level 8"),
                    (9, "Level 9"),
                    (10, "Level 10"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["userData"], name="todo_task_userDat_87366f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["date"], name="todo_task_date_df9361_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["completed"], name="todo_task_complet_91253e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority"], name="todo_task_priorit_ef8ef7_idx"
            ),
        ),
    ]
