# Generated by Django 5.2 on 2025-04-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_task_options_list_to_journal_task_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed", "date", "-priority", "deadline"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_time",
        ),
    ]
