# Generated by Django 5.2 on 2025-04-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Journal", "0003_dayentry_last_modified"),
        ("todo", "0008_rename_chain_task_child_task_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="journalid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taskid",
                to="Journal.rowentry",
            ),
        ),
    ]
